### ISSUE TITLE
SUGGESTION: Add follow/unfollow button on Knacksteem. 

### ISSUE THREAD

**Issue by HarryHeights** [knacksteem/knacksteem.org#146] opened 2019-03-03 11:50 UTC
#### Components

Knacksteem as a community of talented or skillful individual is bound to foster friendship amongst community members. Especially those with the same Knack. 
One of the ways we connect with friends is by following them.
This is currently not possible on Knacksteem. 

#### Proposal

I'm proposing that; the follow/unfollow button be made available on Knacksteem. That is; when I visit the the user's profile.

#### Mockup.

Currently, when I visit another author's profile, there's no follow button. Or, unfollow button; that is in the event when I'm already following that author. 
Here's the profile page of @tykee, who I'm not currently following on Steem.

![tt](https://user-images.githubusercontent.com/40593824/53694687-b57f4280-3db2-11e9-81e9-ef107cb15c90.png)

---

The follow/unfollow button can be add on his profile like this;

![ttjj](https://user-images.githubusercontent.com/40593824/53694696-cc259980-3db2-11e9-95e6-b5b3e9334d0f.png)

#### Benefits 

- Foster friendship on the platform amongst community members.

**Comment by onozasi** [comment] 2019-03-03 18:23
Duplicate of #50

**Closed as completed by onozasi** 2019-03-03 18:23 UTC
